name: "Update test results DB"
on:
  workflow_dispatch:
  push:
    branches:
      - skn0tt-test-results-duckdb

concurrency:
  group: test-results-db
  cancel-in-progress: false

jobs:
  update:
    name: Update DuckDB
    runs-on: ubuntu-22.04
    timeout-minutes: 180
    if: github.repository == 'microsoft/playwright'
    permissions:
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 26
      - run: npm ci
      - run: npm run build
      - working-directory: utils/test-results-db
        run: npm ci
      - name: Download current database
        working-directory: utils/test-results-db
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node cli.ts download
      - name: Ingest new test results
        id: ingest
        working-directory: utils/test-results-db
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_OPTIONS: --max-old-space-size=8192
        run: node cli.ts update --lookback-days 3 --max-size-mb 800
      - name: Upload database
        if: steps.ingest.outputs.imported != '0'
        uses: actions/upload-artifact@v4
        with:
          name: test-results-db
          path: utils/test-results-db/test-results.duckdb
          retention-days: 7
          overwrite: true
